# Generated by Django 5.1.3 on 2025-01-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS', '0002_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(max_length=100),
        ),
    ]
